- react-interactive/src/GenericSlice.tsx
Added ability to include callbacks in GenericSlice for:
- Action Dispatched
- Action Pending
- Action Failed
- Action Complete
Added ability to include custom Thunks in GenericSlice.
> Generic slice Updates

- react-interactive/src/SearchBar.tsx
This matches the Types specified in ModelController.cs
> Added query to SearchType

- react-interactive/package.json
- react-interactive/src/ConfigurableTable.tsx
- react-interactive/src/Modal.tsx
- react-interactive/src/ToolTip.tsx
- Added Portaling of Modals to end of DOM
- Added Portaling of Tooltips to end of DOM
- Added option to portal configTable settings to a div
> Added Portaling

- common-pages/src/StandardSelectPopup.tsx
This addresses Ticket 1084 in GPA Ticketing System
> logic to highlight selected meters in multiselect

- react-interactive/src/SearchBar.tsx
https://support.gridprotectionalliance.org/tickets/1092
> Fix to enums on searhbars selecting multiple

- common-pages/src/Note.tsx
- common-pages/src/SliceInterfaces.tsx
- common-pages/src/ValueList/GroupItem.tsx
> Fix for slice interface generic type to keep up with changes in react

- common-pages/src/SearchBar.tsx
See related pull request for openXDA
> Changed names on search bar default for assets for clarity

- react-interactive/src/Layout/OverlayDrawer.tsx
- react-interactive/src/Layout/SplitDrawer.tsx
- react-interactive/src/Layout/SplitSection.tsx
- react-interactive/src/Layout/VerticalSplit.tsx
- react-interactive/src/Menue/Application.tsx
- react-interactive/src/ToolTip.tsx
- react-interactive/src/index.tsx
- Fixed bug in Tooltip Location when target moves
- Added option to menu to specify additional content in Navbar (for OpenSEE issues)
- Added option to menu to hide sidebar (for OpenSEE issues)
- Added vertical split that can be adjusted by user (for SEBrowser issues)
- Added a semi opaque drawer  (for OpenSEE issues)
> Various fixes

- react-interactive/package.json
- react-interactive/src/Layout/SplitDrawer.tsx
- react-interactive/src/Layout/SplitSection.tsx
- react-interactive/src/Layout/VerticalSplit.tsx
had to republish `react-interactive` since there were some critical issues in that component. Code should be easier to follow as well now
> Refactored code to fix bugs

- application-typings/lib/OpenXDA.ts
These were missed in the previous application Type update
> Updated EventType

- common-pages/package-lock.json
- common-pages/package.json
- helper-functions/package.json
- helper-functions/src/GetTextHeight.ts
- helper-functions/src/GetTextWidth.ts
- react-forms/package-lock.json
- react-forms/package.json
- react-forms/src/Input.tsx
- react-forms/src/MutliCheckBoxSelect.tsx
- react-graph/package-lock.json
- react-graph/package.json
- react-graph/src/AggregatingCircles.tsx
- react-graph/src/Circle.tsx
- react-graph/src/GraphContext.tsx
- react-graph/src/Legend.tsx
- react-graph/src/Line.tsx
- react-graph/src/LineLegend.tsx
- react-graph/src/LineWithThreshold.tsx
- react-graph/src/LogAxis.tsx
- react-graph/src/Plot.tsx
- react-graph/src/index.ts
- react-graph/tsconfig.json
- react-interactive/package-lock.json
- react-interactive/package.json
- react-interactive/src/ConfigurableTable.tsx
- react-interactive/src/Layout/OverlayDrawer.tsx
- react-table/package-lock.json
- react-table/package.json
This includes various fixes in:
`react-graph`
`react-forms` 
`react-interactive`
There is still some clean-up but I ran out of time. 
@gcsantos-gpa once you approve/are happy please republish and update the SEBrowser pull request.
> Various Bug Fixes for SEBrowser

- common-pages/src/SearchBar.tsx
Changed Label from AssetGroup to User per Ticker 1440
> Ticket_1440

- common-pages/src/Note.tsx
- react-graph/src/GraphContext.tsx
- react-graph/src/Legend.tsx
- react-graph/src/Line.tsx
- react-graph/src/LogAxis.tsx
- react-graph/src/Plot.tsx
- react-graph/src/TimeAxis.tsx
- react-graph/src/ValueAxis.tsx
- react-interactive/src/ConfigurableTable.tsx
This is needed to address several SEBrowser issues.
> Notes and Plot updates

- application-typings/lib/PQI.ts
Added PQI Types to match openXDA
> Added PQI Types

- react-forms/src/DatePicker.tsx
- react-forms/src/DateTimeUI/Clock.tsx
- react-forms/src/Input.tsx
- react-graph/src/LogAxis.tsx
- react-graph/src/Plot.tsx
This Fixes a couple of issues:
(1) The Log axis panning got fixed so that it pans the same number of pixels on left and right instead of same number of seconds (since log is nonlinear)
(2) Input will let the user delete everything if it is a number and does not allow NULL so they can type from scratch
(3) Various fixes to Date and Time Picker
> Plot adjustments

- common-pages/src/Note.tsx
It also fixes a Bug that moved the Edit/Delete buttons in the middle when Type and Tag are included
> Added option to include custom Columns in Note Page

- react-forms/src/DateTimeUI/Calender.tsx
- react-interactive/src/ConfigurableTable.tsx
- react-interactive/src/GenericSlice.tsx
- react-interactive/src/SearchBar.tsx
Adds Pagination to GenericSlice
Fixed Calendar Highlight
Fixed Ticket_1486
Temporary fix for Ticket_1485
Fixed Ticket_1340
> Pagination

- react-interactive/src/ConfigurableTable.tsx
- react-interactive/src/ProgressBar.tsx
This cleans up the ProgressBar and also fixes minor Layout issues in ConfigurableTable
> Ticket_1510_1507

- application-typings/lib/SystemCenter.ts
Add ChannelGroup & ChannelGroupDetails interfaces to SystemCenter.
> Add ChannelGroup & ChannelGroupDetails interfaces

- react-forms/src/DatePicker.tsx
- react-forms/src/DateTimeUI/Calender.tsx
- react-forms/src/DateTimeUI/Clock.tsx
This addresses some fixes in the date time pickers including Ticket_1486
> Date time fixes

- application-typings/package-lock.json
- common-pages/package-lock.json
- gpa-symbols/package-lock.json
- helper-functions/package-lock.json
- react-forms/package-lock.json
- react-graph/package-lock.json
- react-interactive/package-lock.json
- react-table/package-lock.json
Updating React is a bigger lift than we can do right now
> Dependency Update to address Vulnberabilites

- application-typings/lib/OpenXDA.ts
Add Event Tag and MATLAB Analytic Interfaces to application typings.
> Event Tag and MATLAB Analytic Interfaces

- react-forms/src/Input.tsx
> Add step='any' to Input to cirucmvent the browser validation messages.

- react-interactive/src/Menue/Application.tsx
- react-interactive/src/Menue/Page.tsx
- Added an optional `Paths` prop to the `Page` component, enabling dynamic routes and eliminating the need for multiple Page components when optional query parameters are needed.
- Added  `isPathActive` function, to handle `NavLink` highlighting for cases with optional query parameters or query parameters in general.
- Modified the `CreateRoute` function to handle the `Paths` prop if it was provided in the `Page` component.
> Enhance Page Component with Dynamic Paths and Improved NavLink Highlighting

- react-interactive/src/ConfigurableTable.tsx
> Fixed Tooltip

- react-forms/src/CheckBox.tsx
- react-forms/src/HelperMessage.tsx
- react-forms/src/TextArea.tsx
- react-interactive/src/ConfigurableTable.tsx
Fixed issue causing positioning to be incorrect.
Increased zIndex so when nested in the Modal Component it will still be visible. 
Added a MinWidth Prop to HelperMessage
Added Helper Message component to CheckBox
> HelperMessage Bugfix & support for Checkbox

- react-interactive/src/ProgressBar.tsx
Fixes several bugs in the Progress bar Layout including:
Top of the circles lines up with top of the Progress bar
remove min height
add key to resolve React error
> Progress Bar Layout Fixes

- helper-functions/src/HexToHsv.ts
- helper-functions/src/HsvtoHex.ts
- helper-functions/src/SpacedColor.ts
- helper-functions/src/index.ts
- react-interactive/src/DropdownButton.tsx
- react-interactive/src/index.tsx
Added the Helper Functions currently in the SEBrowser PR. This should make #185  pass `Lint`
Also Added a Button with Dropdown option
> Added Helper Functions and Dropdown Button

- react-interactive/src/SearchBar.tsx
Ticket_1485
https://support.gridprotectionalliance.org/tickets/1485
> Remove <> option and fix duplicate/missing option.

- helper-functions/.eslintrc
- helper-functions/package-lock.json
- helper-functions/package.json
- helper-functions/src/FindLastIndex.ts
- helper-functions/src/React/useEffectWithPrevious.ts
- helper-functions/src/index.ts
- react-forms/src/TextArea.tsx
- react-interactive/src/ConfigurableTable.tsx
- react-table/src/DynamicTable.tsx
- react-table/src/Table.tsx
Added Ability to move column width in Config Table
Fixed `TextArea` bug causing cursor to jump (matching `Input`)
> Added Ability to move collumn width in Config Table

- react-interactive/package-lock.json
- react-interactive/src/Modal.tsx
Added a prop to Modal Component that will toggle the confirm button based on it's value.
> ShowConfirm Prop

- react-forms/src/DatePicker.tsx
- react-table/src/AdjustableTable/AdjustableTable.tsx
Added ability for TimePicker to return `Null`
Fixed Adjustable Table to change col width when resizing and fixed issue resulting in 2 lines of rows
Fixed Adjustable Table to properly call OnClick
> Sebrowser update changes

- react-interactive/src/Layout/VerticalSplit.tsx
This will make the section divs 100% height to allow use of flex inside
> Added Height to Section

- react-table/src/AdjustableTable/AdjustableColumn.tsx
- react-table/src/AdjustableTable/AdjustableTable.tsx
- react-table/src/AdjustableTable/Column.tsx
Changes to certain aspects of ReactTable:
- Add `style` parameter to the function `Content` requires in `ReactTable.Column`.
- Add `index` parameter to the function `KeySelector` requires in `ReactTable.Table`.
> ReactTable Changes

- application-typings/lib/OpenXDA.ts
Added missing TSX Types in ApplicationTypings.
> issue_SC-25_gemstone

- react-forms/src/DatePicker.tsx
Shows an error in feedback section if the selected date is before 1753.
> Validate date entry, requiring input after 1753-01-01

- react-forms/src/DateTimeUI/Calender.tsx
- react-interactive/src/ProgressBar.tsx
- react-interactive/src/Warning.tsx
SC-4 will need a SystemCenter update in existing pr
SC-71 will also require more SystemCenter work
> SC-71 SC-4 GEM-9

- helper-functions/package-lock.json
- react-forms/package-lock.json
- react-forms/package.json
- react-forms/src/ColorPicker.tsx
- react-forms/src/index.tsx
- react-interactive/package-lock.json
- react-interactive/src/Layout/VerticalSplit.tsx
- Added a ColorPicker component to react-forms
- Fixed issue with the opened drawer label not extending the full available height
> Color-Picker

- react-graph/src/LineLegend.tsx
- Cleaned up naming of states and variables.
- Added the style of the label to the call to getTextWidth() to fix issue with labels not getting correct styles.
> Width bugfix

- react-forms/src/ColorPicker.tsx
Made Colors prop optional and added a default Colors array to be used
> Made Colors props optional and added default colors array

- react-graph/src/LogAxis.tsx
Fixed issue with initial ticks only containing one tick by adding the steps state to the dependency array for the useEffect hook that handles setting the ticks.
> Initial ticks

- react-forms/package-lock.json
- react-forms/src/DatePicker.tsx
- react-forms/src/DateTimeUI/Calender.tsx
- react-forms/src/DateTimeUI/Clock.tsx
- react-forms/src/DateTimeUI/DateTimePopup.tsx
- react-forms/src/Input.tsx
- react-interactive/src/SearchBar.tsx
> SC-75 prevent past date + return null on invalid dates

- react-forms/package.json
- react-forms/src/ArrayCheckBoxes.tsx
By linking labels with their checkbox inputs, you can click on the label to change the state of the checkbox.
> Link array checkbox labels with their checkboxes

- common-pages/src/ErrorBoundary.tsx
- common-pages/src/index.tsx
Added an ErrorBoundary component. Three places come to mind where we could use this common component immediately being `TrenDAP datsources/widgets` and in `EventWidgets`. 
GEM-18
> Added ErrorBoundary component

- react-forms/src/InputWithButton.tsx
- react-forms/src/index.tsx
Added an `InputWithButton` component. This works the same as the `Input` component with the additional props to handle a buttonClick and to customize the button's class and label.
GEM-19
> Added InputWithButton component

- application-typings/lib/OpenXDA.ts
Updated DataFile Model to include ProcessedStatus
> updated Datafile model

- gpa-symbols/src/ReactIcons.tsx
- react-table/src/Paging.tsx
Fixes some issues with the Pagination and adds an SVG Spinner Icon
> Pagination fix

- gpa-symbols/src/ReactIcons.tsx
- react-forms/src/ToggleSwitch.tsx
- react-interactive/src/DropdownButton.tsx
Added `Style` prop to `InputWithButton`.
Added logic to utilized the `Disabled` prop in the `Options` array to disabled dropdown-items.
Added CopyIcon
> Add optional style prop to ToggleSwitch

- react-interactive/src/Menue/Application.tsx
Fix pages and sections rendering in the sidebar and the main div when using legacy navigation.
> GEM-24 Fix Duplicate Navbar Elements

- react-forms/src/ArrayMultiSelect.tsx
- react-forms/src/Select.tsx
- react-forms/src/TimePicker.tsx
> Tdap gemstone

- react-interactive/src/TabSelector.tsx
Fixed dropdown with resizeobserver and dropdown-item classes
> GEM-12 tab selector not showing fix

- react-forms/package.json
> VersionFix

- react-graph/src/PointNode.tsx
Fix condition in child node selection.
> PointNode Fix

- gpa-symbols/src/ReactIcons.tsx
Immediate use case is for EE StreamSplitter Connections page.
> Added RSS Icon

- react-interactive/src/LayoutGrid.tsx
> Added fix to colMax in LayoutGrid

- react-forms/src/DatePicker.tsx
- react-forms/src/DateTimeUI/Calender.tsx
Set Calendar cells to only highlight when date matches input box.
> Fixed DatePicker and Calendar not displaying correct date

- gpa-symbols/src/ReactIcons.tsx
Immediate use case is for EEStreamsplitter.
> Added CirclePlus Icon

- react-interactive/src/LayoutGrid.tsx
Fixed when grid opts for ColMax and LowestSquare number of columns
Line 78
> Fixed Grid Column Number

- common-pages/src/Note.tsx
Removes margin at the bottom of Note component.
> Remove margin note for SC-148

- react-forms/src/RadioButtons.tsx
- react-forms/src/Select.tsx
Allows Type for RadioButtons to be number
> Added number to type

- react-interactive/src/DropdownButton.tsx
- react-interactive/src/Layout/VerticalSplit.tsx
- react-interactive/src/ToolTip.tsx
Added tooltip options for dropdown buttons
> Btn dropdown update

- react-interactive/src/Menue/Page.tsx
Added prop to designate other acceptable pages as active links
> Page Component Active Links

- application-typings/src/OpenXDA.ts
> Gemstone change for SC-196

- application-typings/src/OpenXDA.ts
Supports the following PRs:
https://github.com/GridProtectionAlliance/openXDA/pull/356
https://github.com/GridProtectionAlliance/SystemCenter/pull/506
SC-199
> Added fields needed for APIauth on remote instances

- react-graph/src/Oval.tsx
Optimize logic to set Text Size and centered text on oval.
> Oval Performance Fix

- react-graph/src/HighlightBox.tsx
- react-graph/src/Oval.tsx
- react-graph/src/Plot.tsx
- react-graph/src/index.ts
Added highlight box component
Fix text position in oval
Added prop to hide yAxises in plot
> HighlightBox

- helper-functions/package-lock.json
- helper-functions/package.json
- helper-functions/src/index.ts
- helper-functions/src/useGetContainerPosition.tsx
- react-interactive/src/Menue/Application.tsx
Added a custom hook to be used to get position/size of an element. 
Added overflow styling to sidenav and logic to hide/collapse it.
> Sidebar fix

- common-pages/src/TimeFilter/TimeFilter.tsx
- gpa-symbols/src/ReactIcons.tsx
- react-forms/src/Input.tsx
- react-graph/src/LineLegend.tsx
- react-interactive/src/Alert.tsx
- react-interactive/src/ConfigurableTable/ConfigurableTable.tsx
- react-interactive/src/Pipelines/CSVPipeline.tsx
- react-interactive/src/TabSelector.tsx
Add flag to control helper message
> TimeFilter-Helper

- application-typings/src/OpenXDA.ts
> Removed legacy auth from datapusher

- react-interactive/src/ConfigurableTable/ConfigurableTable.tsx
The Config Table Reset Defaults button is now btn-warning
> GEM-42 Change color of Reset Defaults button

- react-interactive/src/Modal.tsx
Removes the whole footer when there are no buttons shown.
> GEM-37 modal footer

- react-interactive/src/Menue/Application.tsx
- react-interactive/src/Menue/Context.tsx
- react-interactive/src/Menue/Page.tsx
- react-interactive/src/Menue/Section.tsx
<h4>Jira Issue(s)</h4>  
*<h6>[SC-16](https://gridprotectionalliance.atlassian.net/browse/SC-16)</h6>*
<br />
---
<h4>Description</h4>  
<h6>Upgrades and changes to application component to accommodate related system center PR.</h6> 
<br />
---
<h5>Related PRs</h5>  
*<h6>[SystemCenter #606](https://github.com/GridProtectionAlliance/SystemCenter/pull/606)</h6>*  
[SC-16]: https://gridprotectionalliance.atlassian.net/browse/SC-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> App update

- common-pages/src/BulkUpload.tsx
- common-pages/src/RoleAcessErrorPage.tsx
- common-pages/src/index.tsx
- react-interactive/src/GenericSlice.tsx
- react-interactive/src/SearchBar.tsx
- react-interactive/src/ServerErrorIcon.tsx
JIRA Issues:
[GEM-51](https://gridprotectionalliance.atlassian.net/browse/GEM-51)
[GEM-40](https://gridprotectionalliance.atlassian.net/browse/GEM-40)
[GEM-33](https://gridprotectionalliance.atlassian.net/browse/GEM-33)
Required by PR:
[SC #615](https://github.com/GridProtectionAlliance/SystemCenter/pull/615)
[GEM-51]: https://gridprotectionalliance.atlassian.net/browse/GEM-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GEM-40]: https://gridprotectionalliance.atlassian.net/browse/GEM-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GEM-33]: https://gridprotectionalliance.atlassian.net/browse/GEM-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Gemstone fixes

- application-typings/src/Gemstone.ts
- common-pages/src/Pipelines/CSVPipeline.tsx
- gpa-symbols/src/ReactIcons.tsx
- react-forms/src/StylableSelect.tsx
Change Validate function in CsvPipeline to return either a Promise<boolean> or a boolean.
Added Double Chevron icon.
> CsvPipeline Validation

- common-pages/src/ErrorBoundary.tsx
Added optional prop to size ServerErrorIcon and overflow styling to card body.
> ErrorBoundary Sizing

- common-pages/src/TimeFilter/TimeFilter.tsx
- helper-functions/src/GetScrollBarWidth.ts
- helper-functions/src/index.ts
- helper-functions/src/useGetScreenSize.ts
- helper-functions/src/useMediaQuery.ts
- react-forms/src/DatePicker.tsx
- react-forms/src/FileUpload.tsx
- react-graph/src/Legend.tsx
- react-graph/src/LegendContext.tsx
- react-graph/src/LineLegend.tsx
- react-graph/src/Plot.tsx
- react-graph/src/PlotGroup.tsx
- react-graph/src/PlotGroupContext.ts
- react-graph/src/TimeAxis.tsx
- react-graph/src/YValueAxis.tsx
- react-graph/src/index.ts
- react-interactive/src/HelperAlerts/AlertKeys.ts
- react-interactive/src/HelperAlerts/ConfigurableTableAlert.tsx
- react-interactive/src/LayoutGrid.tsx
- react-interactive/src/Menue/Application/Application.tsx
- react-interactive/src/Menue/Application/SideBarContent.tsx
- react-table/src/Table/Table.tsx
- Shortened labels in TimeFilter and added tooltips to DatePicker when input gets cut off.
- Added a PlotGroup/PlotGroupContext to enforce same legend width across multiple plots.
- Added a smallest fontsize to LegendContext so legend entries use the same font size.
- Fix issue in Application with using estimated sidebar width value when collapsed.
- Add border radius to fileupload.
- Added logic to dynamically reduce fontsize in yValueAxis when ticks dont fit.
> Layout Fixes

- .gitignore
- test/jest.config.js
- test/jest.setup.ts
- test/package.json
- test/src/App.d.ts
- test/src/__tests__/react-forms/Checkbox.test.ts
- test/src/__tests__/react-interactive/Alert.test.ts
- test/tsconfig.json
- test/webpack.config.js
Typescript declaration files were added into last pr by error.
Testing is now ran with `npm run tester`. This uses an npm plugin to run the tests after it finishes building.
This is the base branch for the other Testing branches. Merge this first
> Testing: remove declaration files from git

- test/src/App.tsx
- test/src/__tests__/react-interactive/Breadcrumb.test.ts
- test/src/components/react-interactive/Breadcrumb.tsx
**Description**
This pull request introduces end-to-end tests for the Breadcrumb component using Selenium WebDriver and Jest. These tests verify both visual rendering and interactive behavior of the breadcrumb navigation elements.
****
**Changes**
Added two test cases for Breadcrumb.tsx:
Visibility and Props Test: Ensures the breadcrumb component is rendered, displays steps in order, and applies the active class to the current step.
Interaction Test: Validates that non-navigable breadcrumb items do not change the active state, while navigable items do.
> Add Selenium Tests for Breadcrumb Component

- react-interactive/src/DropdownButton.tsx
- test/src/App.tsx
- test/src/__tests__/react-interactive/DropdownButton.test.ts
- test/src/components/react-interactive/DropdownButton.tsx
**Description**
This pull request introduces tests for the Button Dropdown component using Selenium WebDriver and Jest. These tests verify both visual rendering and interactive behavior of the dropdown button element.
****
**Changes**
Adds visual and interaction testing:
- renders dropdown button, size, class, and label
- executes callback on main button click
- shows dropdown menu on toggle click
- renders dropdown items and dividers correctly
- executes callback on enabled dropdown item click
- does not execute callback on disabled dropdown item
> Add Tests for Dropdown Button

- gpa-symbols/src/ReactIcons.tsx
- react-interactive/src/Menue/Application/Application.tsx
- react-interactive/src/Menue/Application/SideBarContent.tsx
Add optional prop to add sidebar text to sidebar.
Improve styling of sidebar to be more dynamic.
> SidebarText

- common-pages/src/BulkUpload.tsx
- react-interactive/src/Menue/Application/SideBarContent.tsx
Remove sidebarUI when collapsed and fix jsdoc comment in bulkupload.
> SidebarFix

- application-typings/src/Gemstone.ts
- common-pages/src/Pipelines/CSVPipeline/CSVFieldContext.ts
- common-pages/src/Pipelines/CSVPipeline/CSVPipeline.tsx
- common-pages/src/index.tsx
Add CSVEditFieldContext for the ability to have EditComponent be a JSX.Element rather than a function that returns a JSX.Component.
> CSVPipelineRework

- react-graph/src/GraphContext.tsx
- react-graph/src/HeatLegend.tsx
- react-graph/src/HeatMapChart.tsx
- react-graph/src/Legend.tsx
- react-graph/src/LegendContext.tsx
- react-graph/src/Line.tsx
- react-graph/src/LineLegend.tsx
- react-graph/src/LineWithThreshold.tsx
- react-graph/src/Plot.tsx
Moved calculations for size to legend from legend components
Added ctrl click support
- Ctrl-Clicking on any item when other items are enabled disables all other items
- Ctrl-Clicking on any item when all other items are disabled enables all items
> Legend improvements

- helper-functions/src/useGetContainerPosition.tsx
- react-forms/src/SearchableSelect.tsx
- react-graph/src/Legend.tsx
Fix call to RequestLegendWidth
Add clientWidth, clientHeight, scrollHeight to getContainerPosition
Fix tpo in searchableselect
> LegendWidthFix

- application-typings/src/SystemCenter.ts
- react-forms/src/MutliCheckBoxSelect.tsx
Support for:
[Pull #778](https://github.com/GridProtectionAlliance/SystemCenter/pull/718)
Additional fix: Console errors from MultiCheckBoxSelect. This isn't a big deal, but it was annoying.
> Minor fixes

- helper-functions/src/IsBool.ts
- helper-functions/src/JoinKeyValuePairs.ts
- helper-functions/src/ParseKeyValuePairs.ts
- helper-functions/src/RegexEncode.ts
- helper-functions/src/ReplaceAll.ts
- helper-functions/src/index.ts
Migrated functions from [GSF](https://github.com/GridProtectionAlliance/gsf/blob/master/Source/Libraries/GSF.Web/Shared/Scripts/gsf.web.client.js).
> GSF Migration

- common-pages/src/BulkUpload.tsx
- react-forms/src/FileUpload.tsx
- react-forms/src/SearchableSelect.tsx
- react-forms/src/StylableSelect.tsx
- react-forms/src/ToggleSwitch.tsx
- react-graph/src/Pill.tsx
- react-graph/src/Plot.tsx
- react-interactive/src/StatusProgressBar.tsx
- react-interactive/src/index.tsx
- Added invalid feedback for stylable/searchable select
- Added logic to update search whenever the record's value changes
> Searchable select fix+enhancemenet

- .gitignore
- react-forms/src/MultiSearchableSelect.tsx
- react-forms/src/SearchableSelect.tsx
- react-forms/src/index.tsx
- react-table/.gitignore
- test/package-lock.json
- test/package.json
Added a MultiSearchableSelect component.
> MultiSearchableSelect

- common-pages/src/ErrorBoundary.tsx
- common-pages/src/Pipelines/CSVPipeline/CSVPipeline.tsx
Required for [TDAP PR 41](https://github.com/GridProtectionAlliance/TrenDAP/pull/41).
> Change in Error Boundry to not have wrapping styling

- application-typings/src/Gemstone.ts
- gpa-symbols/src/ReactIcons.tsx
- react-forms/src/CheckBox.tsx
- react-forms/src/DateTimeUI/DateTimePicker.tsx
- react-forms/src/Input.tsx
- react-forms/src/InputWithButton.tsx
- react-forms/src/MultiInput.tsx
- react-forms/src/MultiSearchableSelect.tsx
- react-forms/src/MutliCheckBoxSelect.tsx
- react-forms/src/RadioButtons.tsx
- react-forms/src/Select.tsx
- react-forms/src/StylableSelect.tsx
- react-forms/src/TextArea.tsx
- react-forms/src/TimePicker.tsx
- react-forms/src/ToggleSwitch.tsx
- react-forms/src/ToolTip.tsx
- react-interactive/src/DecisionHelpTree.tsx
- react-interactive/src/Layout/VerticalSplit.tsx
- react-interactive/src/Warning.tsx
- react-interactive/src/index.tsx
- Added Decision Helper Tree component
- Added logic to delay tooltip from closing to allow for hovering
- Fix bug in SplitSection when removing a section from the DOM.
> Decision Help Tree

- gpa-symbols/src/ReactIcons.tsx
- react-forms/src/MultiSearchableSelect.tsx
- react-forms/src/SearchableSelect.tsx
- react-forms/src/Select.tsx
Added the selected option to select setters
Added icons for security
Added optional strokeWidth prop to ReactIcons
> Select Setter Update
